const SERVERLESS_URL = import.meta.env.VITE_SERVERLESS_URL;
const GENERATE_LINK_MODE_TEST = import.meta.env.VITE_GENERATE_LINK_MODE_TEST;
const UPLOAD_FILE_FOLDER = import.meta.env.VITE_UPLOAD_FILE_FOLDER;
const DATA_MOCK = import.meta.env.VITE_DATA_MOCK;

export default {
  SERVERLESS_URL,
  GENERATE_LINK_MODE_TEST,
  UPLOAD_FILE_FOLDER,
  DATA_MOCK
}